version: 3.9
services:
  api:
    container_name: api
    build: ./api
    ports:
      - 8080:8080
    volumes:
      # ホスト側の./apiをコンテナ側の/workspaceにマウント
      # cachedはマウントのパフォーマンスを向上させるオプション
      - ./api:/workspace:cached

  web:
    container_name: web
    build: ./web
    ports: 
      - 3000:3000
    volumes:
      - ./web:/workspace/:cached
    # これによりapiサーバが先に起動する
    depends_on:
      - api

